version: '3.9'

services:
  educonnect-api:
    container_name: educonnect-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"  # host:container
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__EduConnect=Host=postgres;Port=5432;Database=educonnect;Username=root;Password=example
    volumes:
      - ./logs:/app/logs
    working_dir: /app
    restart: always

  postgres:
    container_name: educonnect-postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
