name: Deploy EduConnect API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on VM
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/EduConnect
            git checkout main
            git pull origin main
            docker-compose down
            docker-compose up --build -d
